set:
  successful: "Updated setting %s to %s"
  failed: "Failed to update the setting %s"
unset:
  successful: "Unset the setting %s"
  failed: "Failed to unset the setting %s"
reset:
  successful: "Reset all of the channel's settings back to default"
  failed: "Failed to reset all of the settings"
  confirmation: "Are you sure you want to reset the channel's settings?"